import { neon } from "@netlify/neon";

type NeonSql = ReturnType<typeof neon>;
type SqlTagResult = ReturnType<NeonSql>;
type SqlQuery = NeonSql["query"];

let sqlClient: NeonSql | null = null;

function getSqlClient() {
  if (!sqlClient) {
    sqlClient = neon();
  }
  return sqlClient;
}

export const sql = Object.assign(
  (strings: TemplateStringsArray, ...values: unknown[]): SqlTagResult => getSqlClient()(strings, ...values),
  {
    query: ((text: string, params?: unknown[]) => getSqlClient().query(text, params)) as SqlQuery,
  },
);

let initPromise: Promise<void> | null = null;

export async function ensureDb() {
  if (!initPromise) {
    initPromise = initialize();
  }
  return initPromise;
}

export async function queryRows<T = unknown>(text: string, params: unknown[] = []) {
  await ensureDb();
  return sql.query(text, params) as Promise<T[]>;
}

export async function queryRow<T = unknown>(text: string, params: unknown[] = []) {
  const rows = await queryRows<T>(text, params);
  return rows[0];
}

async function initialize() {
  await sql`
    CREATE TABLE IF NOT EXISTS rsvps (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      name TEXT NOT NULL,
      email TEXT NOT NULL DEFAULT '',
      phone TEXT,
      attending INTEGER NOT NULL,
      guest_count INTEGER NOT NULL,
      what TEXT,
      meal TEXT,
      created_at TIMESTAMPTZ NOT NULL DEFAULT now()
    )
  `;

  await sql`
    CREATE TABLE IF NOT EXISTS cms_menu_items (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      label TEXT NOT NULL,
      href TEXT NOT NULL,
      position INTEGER NOT NULL DEFAULT 0,
      is_visible INTEGER NOT NULL DEFAULT 1,
      locale TEXT NOT NULL DEFAULT 'en',
      UNIQUE(label, href, locale)
    )
  `;
  await sql`CREATE INDEX IF NOT EXISTS idx_cms_menu_locale ON cms_menu_items(locale)`;

  await sql`
    CREATE TABLE IF NOT EXISTS cms_blocks (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      slug TEXT NOT NULL,
      selector TEXT NOT NULL,
      content_html TEXT NOT NULL,
      position INTEGER NOT NULL DEFAULT 0,
      is_visible INTEGER NOT NULL DEFAULT 1,
      locale TEXT NOT NULL DEFAULT 'en',
      updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
      UNIQUE(slug, locale)
    )
  `;
  await sql`CREATE INDEX IF NOT EXISTS idx_cms_blocks_locale ON cms_blocks(locale)`;

  await sql`
    CREATE TABLE IF NOT EXISTS cms_meta_localized (
      locale TEXT PRIMARY KEY,
      bride_name TEXT NOT NULL,
      groom_name TEXT NOT NULL,
      event_date TEXT,
      event_location TEXT,
      hero_headline TEXT,
      hero_subtext TEXT,
      hero_shape_url TEXT,
      invitation_gate_background_url TEXT,
      background_music_url TEXT,
      brand_text TEXT,
      updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
    )
  `;
  await sql`ALTER TABLE cms_meta_localized ADD COLUMN IF NOT EXISTS hero_shape_url TEXT`;
  await sql`ALTER TABLE cms_meta_localized ADD COLUMN IF NOT EXISTS invitation_gate_background_url TEXT`;
  await sql`ALTER TABLE cms_meta_localized ADD COLUMN IF NOT EXISTS background_music_url TEXT`;
  await sql`
    INSERT INTO cms_meta_localized (
      locale,
      bride_name,
      groom_name,
      event_date,
      event_location,
      hero_headline,
      hero_subtext,
      hero_shape_url,
      invitation_gate_background_url,
      background_music_url,
      brand_text
    )
    VALUES (
      'en',
      'Jane',
      'Peter',
      'November 15, 2026',
      'Yerevan, Armenia',
      'Save the Date',
      'We Are Getting Married November 15, 2026',
      '/template-assets/images/html/tf/habibi/assets/images/wedding-date/1.png',
      '/template-assets/images/html/tf/habibi/assets/images/rsvp/img-3.jpg',
      '/media/perfect.mp3',
      'Habibi'
    )
    ON CONFLICT(locale) DO NOTHING
  `;
  await sql`
    UPDATE cms_meta_localized
    SET hero_shape_url = '/template-assets/images/html/tf/habibi/assets/images/wedding-date/1.png'
    WHERE hero_shape_url IS NULL
  `;
  await sql`
    UPDATE cms_meta_localized
    SET invitation_gate_background_url = '/template-assets/images/html/tf/habibi/assets/images/rsvp/img-3.jpg'
    WHERE invitation_gate_background_url IS NULL
  `;
  await sql`
    UPDATE cms_meta_localized
    SET background_music_url = '/media/perfect.mp3'
    WHERE background_music_url IS NULL
  `;

  await sql`
    CREATE TABLE IF NOT EXISTS cms_couple_section (
      locale TEXT PRIMARY KEY,
      left_name TEXT NOT NULL,
      left_bio TEXT,
      left_icon_url TEXT,
      left_facebook_url TEXT,
      left_twitter_url TEXT,
      left_instagram_url TEXT,
      right_name TEXT NOT NULL,
      right_bio TEXT,
      right_icon_url TEXT,
      right_facebook_url TEXT,
      right_twitter_url TEXT,
      right_instagram_url TEXT,
      center_photo_url TEXT,
      center_overlay_url TEXT,
      updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
    )
  `;
  await sql`
    INSERT INTO cms_couple_section (
      locale,
      left_name,
      left_bio,
      left_icon_url,
      left_facebook_url,
      left_twitter_url,
      left_instagram_url,
      right_name,
      right_bio,
      right_icon_url,
      right_facebook_url,
      right_twitter_url,
      right_instagram_url,
      center_photo_url,
      center_overlay_url
    ) VALUES (
      'en',
      'Robert Peter',
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Urna orci auctor vitae nisl. Erat fringilla pellentesque amet tempus. Commodo mi vitae, sagittis blandit.',
      '/template-assets/images/html/tf/habibi/assets/images/couple/vector-1.svg',
      '#',
      '#',
      '#',
      'Jane Margrate',
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Urna orci auctor vitae nisl. Erat fringilla pellentesque amet tempus. Commodo mi vitae, sagittis blandit.',
      '/template-assets/images/html/tf/habibi/assets/images/couple/vector-2.svg',
      '#',
      '#',
      '#',
      '/template-assets/images/html/tf/habibi/assets/images/couple/3.jpg',
      '/template-assets/images/html/tf/habibi/assets/images/couple/couple-flower.png'
    )
    ON CONFLICT(locale) DO NOTHING
  `;

  await sql`
    CREATE TABLE IF NOT EXISTS cms_event_section (
      locale TEXT PRIMARY KEY,
      eyebrow TEXT NOT NULL,
      heading TEXT NOT NULL,
      items_json TEXT NOT NULL,
      updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
    )
  `;
  await sql`
    INSERT INTO cms_event_section (locale, eyebrow, heading, items_json)
    VALUES (
      'en',
      'Our Wedding',
      'When & Where',
      '[{"title":"The Reception","image_url":"/template-assets/images/html/tf/habibi/assets/images/event/4.jpg","time":"1:00 PM - 2:30 PM","address":"4517 Washington Ave. Manchester, Kentucky 39495","map_url":null,"is_visible":true},{"title":"The Ceremony","image_url":"/template-assets/images/html/tf/habibi/assets/images/event/5.jpg","time":"1:00 PM - 2:30 PM","address":"4517 Washington Ave. Manchester, Kentucky 39495","map_url":null,"is_visible":true},{"title":"The Party","image_url":"/template-assets/images/html/tf/habibi/assets/images/event/6.jpg","time":"1:00 PM - 2:30 PM","address":"4517 Washington Ave. Manchester, Kentucky 39495","map_url":null,"is_visible":true}]'
    )
    ON CONFLICT(locale) DO NOTHING
  `;

  await sql`
    CREATE TABLE IF NOT EXISTS cms_media (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      collection TEXT NOT NULL,
      image_url TEXT NOT NULL,
      title TEXT,
      description TEXT,
      link_url TEXT,
      position INTEGER NOT NULL DEFAULT 0,
      locale TEXT NOT NULL DEFAULT 'en',
      created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
      updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
    )
  `;
  await sql`CREATE INDEX IF NOT EXISTS idx_cms_media_collection_locale ON cms_media(collection, locale)`;

  await sql`
    CREATE TABLE IF NOT EXISTS invitees (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      first_name TEXT,
      last_name TEXT,
      email TEXT,
      phone TEXT,
      locale TEXT NOT NULL DEFAULT 'en',
      invite_code TEXT NOT NULL UNIQUE,
      status TEXT NOT NULL DEFAULT 'pending',
      attending INTEGER,
      guest_count INTEGER,
      response_note TEXT,
      responded_at TIMESTAMPTZ,
      created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
      updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
    )
  `;
  await sql`CREATE INDEX IF NOT EXISTS idx_invitees_status ON invitees(status)`;
  await sql`CREATE INDEX IF NOT EXISTS idx_invitees_locale ON invitees(locale)`;

  await sql`
    CREATE TABLE IF NOT EXISTS cms_media_collections (
      collection TEXT PRIMARY KEY,
      label TEXT NOT NULL
    )
  `;
  await sql`
    INSERT INTO cms_media_collections (collection, label) VALUES
      ('hero_slider', 'Hero Slider'),
      ('blog_posts', 'Blog Posts'),
      ('rsvp_images', 'RSVP Form Images')
    ON CONFLICT(collection) DO NOTHING
  `;
}
